defaults:
  - train_transform: Identity
  - test_transform: Identity
  - _self_

name: CCAD_vers_v0_1
global_batch_size: 16
num_classes: 8
height: 24
width: 24
num_patches: 576
norm_path: ${data_dir}
temporal_dropout: 0.5

train_dataset:
  _partial_: true
  _target_: data.CCAD.CCAD
  path: ${data_dir}
  modalities: ${modalities}
  transform: ${dataset.train_transform}
  norm_path: ${dataset.norm_path}
  split: train
  temporal_dropout: ${dataset.temporal_dropout}

val_dataset:
  _partial_: true
  _target_: data.CCAD.CCAD
  path: ${data_dir}
  modalities: ${modalities}
  transform: ${dataset.test_transform}
  norm_path: ${dataset.norm_path}
  split: val

test_dataset:
  _partial_: true
  _target_: data.CCAD.CCAD
  path: ${data_dir}
  modalities: ${modalities}
  transform: ${dataset.test_transform}
  norm_path: ${dataset.norm_path}
  split: test
